project:
  type: website

website:
  page-navigation: true
  title: "MATH/COSC 3570 - Spring 2026"
  description: "Homepage for MATH/COSC 3570 - Introduction to Data Science at Marquette University, Spring 2026."
  site-url: "https://math3570-s26.github.io/website/"

  repo-url: https://github.com/math3570-s26/website
  repo-actions: [edit, issue]

  open-graph: true

  # twitter-card:
  #   creator: "@minebocek"
  #   image: "images/twitter-card.png"

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Cheng-Han Yu"
    background: "#008080"

  sidebar:
    background: "#008080"
    logo: "/images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/math3570-s26
        text: "GitHub organization"
      # - icon: code-square
      #   href: https://cmgr.oit.duke.edu/containers
      #   text: "RStudio Containers"
      - icon: person-fill
        href: https://d2l.mu.edu/d2l/home/630428
        text: "D2L"

    style: docked
    search: true
    collapse-level: 0
    contents:
      - section: "Course information"
        contents:
          # - href: course-news.qmd
          #   text: News/Annoucements
          - href: course-overview.qmd
            text: Overview
          - href: index.qmd
            text: Schedule
          - href: course-syllabus.qmd
            text: Syllabus

      - section: "AI Activities"
        contents:
          - href: ai_act_guide.qmd
            text: Guideline and Policy
          - href: ai_example.qmd
            text: AI Project Example
          - href: ai.qmd
            text: AI Project Topics

      - section: "Mini Project"
        contents:
          - href: project.qmd
            text: Topics and Works

      - section: "Final Project"
        contents:
          - href: present-description-final.qmd
            text: Guideline and Policy
          - href: present-work-final.qmd
            text: Project Group and Proposal


      # - section: "Weekly materials"
      #   contents:
      #     - href: weeks/week-1.qmd
      #       text: "Week 1"
      #     - href: weeks/week-2.qmd
      #       text: "Week 2"
      #     - href: weeks/week-3.qmd
      #       text: "Week 3"
      #     - href: weeks/week-4.qmd
      #       text: "Week 4"
      #     - href: weeks/week-5.qmd
      #       text: "Week 5"
      #     - href: weeks/week-6.qmd
      #       text: "Week 6"
      #     - href: weeks/week-7.qmd
      #       text: "Week 7"
      #     - href: weeks/week-8.qmd
      #       text: "Week 8"
      #     - href: weeks/week-9.qmd
      #       text: "Week 9"
      #     - href: weeks/week-10.qmd
      #       text: "Week 10"
      #     - href: weeks/week-11.qmd
      #       text: "Week 11"
      #     - href: weeks/week-12.qmd
      #       text: "Week 12"
      #     - href: weeks/week-13.qmd
      #       text: "Week 13"
      #     - href: weeks/week-14.qmd
      #       text: "Week 14"
      #     - href: weeks/week-15.qmd
      #       text: "Week 15"
      #     - href: weeks/week-16.qmd
      #       text: "Week 16"

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto
editor: visual